version: "3"
services:
  chrome:
    image: seleniarm/standalone-chromium:latest
    hostname: chrome
    privileged: true
    shm_size: 2gb
    ports:
      - "4441:4444"
      - "7901:7900"
    environment:
      - SE_VNC_NO_PASSWORD=1
      - SE_NODE_MAX_SESSIONS=1

  firefox:
    image: seleniarm/standalone-firefox:latest
    hostname: chrome
    privileged: true
    shm_size: 2gb
    ports:
      - "4442:4444"
      - "7902:7900"
    environment:
      - SE_VNC_NO_PASSWORD=1
      - SE_NODE_MAX_SESSIONS=1

  edge:
    image: selenium/standalone-edge:latest
    hostname: edge
    privileged: true
    shm_size: 2gb
    ports:
      - "4443:4444"
      - "7903:7900"
    environment:
      - SE_VNC_NO_PASSWORD=1
      - SE_NODE_MAX_SESSIONS=1