# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  workflow_dispatch:
    inputs:
      browsername:
        type: string
        description: "Browser Name: "
        default: chrome
      xmlfilename:
        type: string
        description: "Enter xml file name: "
        default: TestNG.xml
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with TestNG xml files
      run: >
        mvn clean test
        -Dsurefire.suiteXmlFiles=${{inputs.xmlfilename}}
        -DbrowserName=${{inputs.browsername}}
        -Dplatform=GitHubActions
        -Dmaven.test.failure.ignore=true

#Report Generation
    - name: archive report artifact
      uses: actions/upload-artifact@v3
      with:
        name: sparkHTML
        path: ./Report/*.html
